# Generated by Django 3.0.6 on 2020-05-10 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion_cargo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id_carro', models.IntegerField(primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
            ],
            options={
                'db_table': 'carro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion_ciudad', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ciudad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('user_cliente', models.CharField(max_length=50)),
                ('pass_cliente', models.CharField(max_length=50)),
                ('direccion_calle', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion_numero', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=35, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('comuna_id_ciudad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion_comuna', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleCarro',
            fields=[
                ('id_detalle_carro', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'detalle_carro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleOrdenDeCompra',
            fields=[
                ('id_detalle', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_compra', models.IntegerField()),
            ],
            options={
                'db_table': 'detalle_orden_de_compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_detalle_venta', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('venta_id_tipo_venta', models.BooleanField()),
            ],
            options={
                'db_table': 'detalle_venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('rut_empresa', models.IntegerField(primary_key=True, serialize=False)),
                ('dv_empresa', models.CharField(max_length=2)),
                ('nombre_empresa', models.CharField(max_length=50)),
                ('rol_empresa', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FamilyProduct',
            fields=[
                ('id_family', models.IntegerField(primary_key=True, serialize=False)),
                ('desc_family', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'family_product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('rut_funcionario', models.IntegerField(primary_key=True, serialize=False)),
                ('dv_funcionario', models.CharField(max_length=2)),
                ('nombre_funcionario', models.CharField(max_length=50)),
                ('apellido_funcionario', models.CharField(max_length=50)),
                ('user_funcionario', models.CharField(max_length=50)),
                ('pass_funcionario', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'funcionario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenDeCompra',
            fields=[
                ('id_orden', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('total', models.IntegerField()),
                ('es_nula', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'orden_de_compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonaNatural',
            fields=[
                ('rut_natural', models.IntegerField(primary_key=True, serialize=False)),
                ('dv_natural', models.CharField(max_length=2)),
                ('nombre_natural', models.CharField(max_length=50)),
                ('apellido_natural', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'persona_natural',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('stock_critico', models.IntegerField()),
                ('fk_id_familia', models.IntegerField()),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=25)),
                ('fono', models.BigIntegerField()),
                ('rubro', models.CharField(max_length=50)),
                ('user_proveedor', models.CharField(max_length=50)),
                ('pass_proveedor', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoProduct',
            fields=[
                ('id_product', models.IntegerField(primary_key=True, serialize=False)),
                ('desc_product', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'tipo_product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoVenta',
            fields=[
                ('id_tipo_venta', models.BooleanField(primary_key=True, serialize=False)),
                ('descripcion_tipo_vena', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField()),
                ('total', models.IntegerField()),
                ('es_nula', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('producto_id_producto', models.OneToOneField(db_column='producto_id_producto', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='home.Producto')),
                ('direccion_imagen', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'imagen',
                'managed': False,
            },
        ),
    ]
