# Generated by Django 3.0.6 on 2020-05-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=35, unique=True, verbose_name='email')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='fecha creacion')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='ultimo login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('tipo_cliente', models.CharField(max_length=50)),
                ('direccion_calle', models.CharField(max_length=50)),
                ('direccion_numero', models.CharField(max_length=50)),
                ('comuna', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('p_natural_rut', models.CharField(max_length=50, verbose_name='rut')),
                ('p_natural_nombre', models.CharField(max_length=50)),
                ('p_natural_apellido', models.CharField(max_length=50)),
                ('empresa_rut', models.CharField(max_length=50)),
                ('empresa_nombre', models.CharField(max_length=50)),
                ('empresa_rol', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
