# Generated by Django 3.0.6 on 2020-05-11 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='p_natural_rut',
            field=models.CharField(max_length=50),
        ),
    ]
