# Generated by Django 3.0.7 on 2020-07-12 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_direcciondespacho'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direcciondespacho',
            old_name='direccion',
            new_name='calle',
        ),
        migrations.RemoveField(
            model_name='direcciondespacho',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='direcciondespacho',
            name='comuna',
        ),
        migrations.AddField(
            model_name='direcciondespacho',
            name='comentario',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='direcciondespacho',
            name='numero',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='direcciondespacho',
            name='zipcode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='empresa_nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre empresa'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='empresa_rol',
            field=models.CharField(max_length=50, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='empresa_rut',
            field=models.CharField(max_length=50, verbose_name='Rut empresa'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='p_natural_nombre',
            field=models.CharField(help_text='Campo requerido', max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='p_natural_rut',
            field=models.CharField(help_text='Campo requerido', max_length=50, verbose_name='Rut'),
        ),
    ]
